/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator1;

/**
 *
 * @author RASHMI
 */
public class Calculator1 extends javax.swing.JFrame {
    double firstnum;
    double secondnum;
    double result;
    String operation;
    
   

   
    public Calculator1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_display = new javax.swing.JTextField();
        btn02 = new javax.swing.JButton();
        btn03 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn04 = new javax.swing.JButton();
        btn06 = new javax.swing.JButton();
        btn07 = new javax.swing.JButton();
        btn08 = new javax.swing.JButton();
        btn09 = new javax.swing.JButton();
        btn00 = new javax.swing.JButton();
        btn001 = new javax.swing.JButton();
        btn002 = new javax.swing.JButton();
        btn003 = new javax.swing.JButton();
        btn004 = new javax.swing.JButton();
        btn05 = new javax.swing.JButton();
        btn006 = new javax.swing.JButton();
        btn005 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_display.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_displayActionPerformed(evt);
            }
        });

        btn02.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn02.setText("2");
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });

        btn03.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn03.setText("3");
        btn03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn03ActionPerformed(evt);
            }
        });

        btn01.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn01.setText("1");
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });

        btn04.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn04.setText("4");
        btn04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn04ActionPerformed(evt);
            }
        });

        btn06.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn06.setText("6");
        btn06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn06ActionPerformed(evt);
            }
        });

        btn07.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn07.setText("7");
        btn07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn07ActionPerformed(evt);
            }
        });

        btn08.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn08.setText("8");
        btn08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn08ActionPerformed(evt);
            }
        });

        btn09.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn09.setText("9");
        btn09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn09ActionPerformed(evt);
            }
        });

        btn00.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn00.setText("0");
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });

        btn001.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn001.setText("+");
        btn001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn001ActionPerformed(evt);
            }
        });

        btn002.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn002.setText("-");
        btn002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn002ActionPerformed(evt);
            }
        });

        btn003.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn003.setText("/");
        btn003.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn003ActionPerformed(evt);
            }
        });

        btn004.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn004.setText("*");
        btn004.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn004ActionPerformed(evt);
            }
        });

        btn05.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn05.setText("5");
        btn05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn05ActionPerformed(evt);
            }
        });

        btn006.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn006.setText("=");
        btn006.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn006ActionPerformed(evt);
            }
        });

        btn005.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn005.setText("c");
        btn005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn005ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn5.setText(".");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btn01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn02)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn03)
                        .addGap(18, 18, 18)
                        .addComponent(btn04))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn09)
                            .addComponent(btn003)
                            .addComponent(btn05))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn06)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn07)
                                .addGap(18, 18, 18)
                                .addComponent(btn08))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(61, 61, 61)
                                    .addComponent(btn006, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn00)
                                    .addGap(17, 17, 17)
                                    .addComponent(btn001)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn002)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn004)
                                .addGap(18, 18, 18)
                                .addComponent(btn5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btn005, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txt_display, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txt_display, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn02)
                    .addComponent(btn03)
                    .addComponent(btn01)
                    .addComponent(btn04))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn06)
                    .addComponent(btn08)
                    .addComponent(btn07)
                    .addComponent(btn05))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn09)
                    .addComponent(btn00)
                    .addComponent(btn001)
                    .addComponent(btn002))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn004)
                            .addComponent(btn003)
                            .addComponent(btn5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn005)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn006)
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn04ActionPerformed
        // TODO add your handling code here:
        String enternumber=txt_display.getText()+btn04.getText();
        txt_display.setText(enternumber);
    }//GEN-LAST:event_btn04ActionPerformed

    private void txt_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_displayActionPerformed

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        // TODO adSSd your handling code here:
        String enternumber=txt_display.getText()+btn01.getText();
        txt_display.setText(enternumber);
        
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
String enternumber=txt_display.getText()+btn02.getText();
        txt_display.setText(enternumber);        // TODO add your handling code here:
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn03ActionPerformed
        // TODO add your handling code here:
        String enternumber=txt_display.getText()+btn03.getText();
        txt_display.setText(enternumber);
    }//GEN-LAST:event_btn03ActionPerformed

    private void btn06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn06ActionPerformed
        // TODO add your handling code here:
        String enternumber=txt_display.getText()+btn06.getText();
        txt_display.setText(enternumber);
    }//GEN-LAST:event_btn06ActionPerformed

    private void btn05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn05ActionPerformed
        // TODO add your handling code here:
        String enternumber=txt_display.getText()+btn05.getText();
        txt_display.setText(enternumber);
    }//GEN-LAST:event_btn05ActionPerformed

    private void btn07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn07ActionPerformed
        // TODO add your handling code here:
        String enternumber=txt_display.getText()+btn07.getText();
        txt_display.setText(enternumber);
    }//GEN-LAST:event_btn07ActionPerformed

    private void btn08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn08ActionPerformed
        // TODO add your handling code here:
        String enternumber=txt_display.getText()+btn08.getText();
        txt_display.setText(enternumber);
    }//GEN-LAST:event_btn08ActionPerformed

    private void btn09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn09ActionPerformed
        // TODO add your handling code here:
        String enternumber=txt_display.getText()+btn09.getText();
        txt_display.setText(enternumber);
    }//GEN-LAST:event_btn09ActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        // TODO add your handling code here:
        String enternumber=txt_display.getText()+btn00.getText();
        txt_display.setText(enternumber);
    }//GEN-LAST:event_btn00ActionPerformed

    private void btn001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn001ActionPerformed
      firstnum = Double.parseDouble(txt_display.getText());
      txt_display.setText("");
      operation="+";
      
    }//GEN-LAST:event_btn001ActionPerformed

    private void btn002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn002ActionPerformed
         firstnum = Double.parseDouble(txt_display.getText());
      txt_display.setText("");
      operation="-";
    }//GEN-LAST:event_btn002ActionPerformed

    private void btn003ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn003ActionPerformed
         firstnum = Double.parseDouble(txt_display.getText());
      txt_display.setText("");
      operation="/";
    }//GEN-LAST:event_btn003ActionPerformed

    private void btn004ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn004ActionPerformed
         firstnum = Double.parseDouble(txt_display.getText());
      txt_display.setText("");
      operation="*";
    }//GEN-LAST:event_btn004ActionPerformed

    private void btn006ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn006ActionPerformed
        String answer;
        secondnum=Double.parseDouble(txt_display.getText());
        if(operation=="+")
        {
            result=firstnum+secondnum;
            answer=String.format("%.0f",result);
            txt_display.setText(answer);
        }
         if(operation=="-")
        {
            result=firstnum-secondnum;
            answer=String.format("%.0f",result);
            txt_display.setText(answer);
        }
          if(operation=="/")
        {
            result=firstnum/secondnum;
            answer=String.format("%.0f",result);
            txt_display.setText(answer);
        }
          if(operation=="*")
        {
            result=firstnum*secondnum;
            answer=String.format("%.0f",result);
            txt_display.setText(answer);
        }
        
        
    }//GEN-LAST:event_btn006ActionPerformed

    private void btn005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn005ActionPerformed
        // TODO add your handling code here:
         txt_display.setText("");
    }//GEN-LAST:event_btn005ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
          String enternumber=txt_display.getText()+ btn5.getText();
        txt_display.setText(enternumber);
    }//GEN-LAST:event_btn5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator1().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn001;
    private javax.swing.JButton btn002;
    private javax.swing.JButton btn003;
    private javax.swing.JButton btn004;
    private javax.swing.JButton btn005;
    private javax.swing.JButton btn006;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn03;
    private javax.swing.JButton btn04;
    private javax.swing.JButton btn05;
    private javax.swing.JButton btn06;
    private javax.swing.JButton btn07;
    private javax.swing.JButton btn08;
    private javax.swing.JButton btn09;
    private javax.swing.JButton btn5;
    private javax.swing.JTextField txt_display;
    // End of variables declaration//GEN-END:variables
}
